// config.bin - 21:23:54 04/07/15, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class DefaultEventhandlers;	// External class reference

class CfgPatches {
	class 11eBP_Gilet {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"A3_Characters_F_BLUFOR","A3_Characters_F_INDEP","A3_Weapons_F_Ammoboxes","A3_Characters_F_EPB","A3_Characters_F_Civil","A3_Characters_F_Gamma"};
	};
};

class cfgWeapons {
	class ItemInfo;	// External class reference
	class Vest_Base;	// External class reference
	class Vest_Camo_Base;	// External class reference
	class Vest_NoCamo_Base;	// External class reference
	class V_PlateCarrierIA1_dgtl;	// External class reference
	
	class V_PlateCarrier2_rgr;
	
   // class Vest_Base_F;
    class VestItem;
    
    class 11eBP_Vest_cbr : V_PlateCarrier2_rgr {
        scope = 2;
        displayName = "11eBP Gilet Coyote";
        picture = "\A3\characters_f\Data\UI\icon_V_plate_carrier_1_CA.paa";
        model = "\A3\Characters_F\BLUFOR\equip_b_vest02";
        hiddenSelections[] = {"camo"};
        hiddenSelectionsTextures[] = {"\11eBP_Gilet\data\11eBP_Vest_cbr_co.paa"};
        
        class ItemInfo : VestItem {
            uniformModel = "\A3\Characters_F\BLUFOR\equip_b_vest02";
            containerClass = "Supply140";
            mass = 50;
            armor = 25;
            passThrough = 0.7;
            hiddenSelections[] = {"camo"};
        };
	};
	
	class 11eBP_Vest_blk : V_PlateCarrier2_rgr {
        scope = 2;
        displayName = "11eBP Gilet Noir";
        picture = "\A3\characters_f\Data\UI\icon_V_plate_carrier_1_CA.paa";
        model = "\A3\Characters_F\BLUFOR\equip_b_vest02";
        hiddenSelections[] = {"camo"};
        hiddenSelectionsTextures[] = {"\11eBP_Gilet\data\11eBP_Vest_blk_co.paa"};
        
        class ItemInfo : VestItem {
            uniformModel = "\A3\Characters_F\BLUFOR\equip_b_vest02";
            containerClass = "Supply140";
            mass = 50;
            armor = 25;
            passThrough = 0.7;
            hiddenSelections[] = {"camo"};
        };
	};
	
	class 11eBP_Vest_khk : V_PlateCarrier2_rgr {
        scope = 2;
        displayName = "11eBP Gilet Tan";
        picture = "\A3\characters_f\Data\UI\icon_V_plate_carrier_1_CA.paa";
        model = "\A3\Characters_F\BLUFOR\equip_b_vest02";
        hiddenSelections[] = {"camo"};
        hiddenSelectionsTextures[] = {"\11eBP_Gilet\data\11eBP_Vest_khk_co.paa"};
        
        class ItemInfo : VestItem {
            uniformModel = "\A3\Characters_F\BLUFOR\equip_b_vest02";
            containerClass = "Supply140";
            mass = 50;
            armor = 25;
            passThrough = 0.7;
            hiddenSelections[] = {"camo"};
        };
	};
	
	class 11eBP_Vest_rgr : V_PlateCarrier2_rgr {
        scope = 2;
        displayName = "11eBP Gilet Olive";
        picture = "\A3\characters_f\Data\UI\icon_V_plate_carrier_1_CA.paa";
        model = "\A3\Characters_F\BLUFOR\equip_b_vest02";
        hiddenSelections[] = {"camo"};
        hiddenSelectionsTextures[] = {"\11eBP_Gilet\data\11eBP_Vest_rgr_co.paa"};
        
        class ItemInfo : VestItem {
            uniformModel = "\A3\Characters_F\BLUFOR\equip_b_vest02";
            containerClass = "Supply140";
            mass = 50;
            armor = 25;
            passThrough = 0.7;
            hiddenSelections[] = {"camo"};
        };
	};
	
	class 11eBP_Vest_lt : V_PlateCarrier2_rgr {
        scope = 2;
        displayName = "11eBP Gilet Rieper";
        picture = "\A3\characters_f\Data\UI\icon_V_plate_carrier_1_CA.paa";
        model = "\A3\Characters_F\BLUFOR\equip_b_vest02";
        hiddenSelections[] = {"camo"};
        hiddenSelectionsTextures[] = {"\11eBP_Gilet\data\11eBP_Vest_lt_co.paa"};
        
        class ItemInfo : VestItem {
            uniformModel = "\A3\Characters_F\BLUFOR\equip_b_vest02";
            containerClass = "Supply140";
            mass = 50;
            armor = 25;
            passThrough = 0.7;
            hiddenSelections[] = {"camo"};
        } };
	};
	

	
};

//V_PlateCarrier2_rgr
//V_PlateCarrier3_rgr